name: CI

on:
  push:
    paths:
    - '**.kt'
    - '**.kts'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: |
          git submodule update --init --recursive
          cd kaliningraph && ./gradlew publishToMavenLocal --stacktrace -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2G" && cd .. && ./gradlew publishToMavenLocal --stacktrace -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2G"
          cd core && ../gradlew allTests --stacktrace
          ./gradlew test --stacktrace
